#!/usr/bin/env python3
#
# Repro for the GPU out-of-bounds fault in Lagrangian bubble void-fraction
# smearing (m_bubbles_EL_kernels.fpp:244, s_compute_stddsv).
#
# This is the generated test case 80CC6F73 ("3D -> Lagrange Bubbles -> Two-way
# Coupling -> Inertial Bubbles -> drag_model=0 -> fd_order=1") with t_step_stop
# raised 50 -> 200 to pass the ~step-96 fault.
#
# BUILD:
#   ./mfc.sh build --gpu acc --mpi --case-optimization #       -i repro_lagrange_oob/case.py -t pre_process simulation -j "$(nproc)"
#
# RUN (aborts at ~step 96 with "call to cuStreamSynchronize returned error 700
# (CUDA_ERROR_ILLEGAL_ADDRESS)"):
#   ./mfc.sh run repro_lagrange_oob/case.py -t pre_process simulation -n 1 #       --gpu acc --mpi --case-optimization
#
# input/lag_bubbles.dat must sit alongside this file (see input/).

import json
import argparse

parser = argparse.ArgumentParser(prog='repro_lagrange_oob', description='Lagrange GPU OOB repro (80CC6F73, 200 steps)')
parser.add_argument('--mfc', type=json.loads, default='{}', metavar='DICT')
ARGS = vars(parser.parse_args())

case = {
    "run_time_info": "T",
    "m": 24,
    "n": 24,
    "p": 24,
    "dt": 1e-06,
    "t_step_start": 0,
    "t_step_stop": 200,
    "t_step_save": 200,
    "num_patches": 3,
    "model_eqns": 2,
    "alt_soundspeed": "F",
    "num_fluids": 2,
    "mpp_lim": "F",
    "mixture_err": "F",
    "time_stepper": 3,
    "recon_type": 1,
    "weno_order": 5,
    "weno_eps": 1e-16,
    "mapped_weno": "F",
    "null_weights": "F",
    "mp_weno": "F",
    "riemann_solver": 2,
    "wave_speeds": 1,
    "avg_state": 2,
    "format": 1,
    "precision": 2,
    "patch_icpp(1)%pres": 1.0,
    "patch_icpp(1)%alpha_rho(1)": 0.96,
    "patch_icpp(1)%alpha(1)": 0.04,
    "patch_icpp(2)%pres": 1.0,
    "patch_icpp(2)%alpha_rho(1)": 0.96,
    "patch_icpp(2)%alpha(1)": 0.04,
    "patch_icpp(3)%pres": 1.0,
    "patch_icpp(3)%alpha_rho(1)": 0.96,
    "patch_icpp(3)%alpha(1)": 0.04,
    "fluid_pp(1)%gamma": 0.16,
    "fluid_pp(1)%pi_inf": 3515.0,
    "fluid_pp(1)%cv": 0.0,
    "fluid_pp(1)%qv": 0.0,
    "fluid_pp(1)%qvp": 0.0,
    "bubbles_euler": "F",
    "bubble_model": 2,
    "polytropic": "F",
    "polydisperse": "F",
    "thermal": 3,
    "patch_icpp(1)%r0": 1,
    "patch_icpp(1)%v0": 0,
    "patch_icpp(2)%r0": 1,
    "patch_icpp(2)%v0": 0,
    "patch_icpp(3)%r0": 1,
    "patch_icpp(3)%v0": 0,
    "qbmm": "F",
    "dist_type": 2,
    "poly_sigma": 0.3,
    "sigR": 0.1,
    "sigV": 0.1,
    "rhoRV": 0.0,
    "acoustic_source": "T",
    "num_source": 1,
    "acoustic(1)%loc(1)": 0.5,
    "acoustic(1)%mag": 20000.0,
    "acoustic(1)%length": 0.25,
    "acoustic(1)%dir": 1.0,
    "acoustic(1)%npulse": 1,
    "acoustic(1)%pulse": 1,
    "rdma_mpi": "F",
    "bubbles_lagrange": "T",
    "lag_params%nBubs_glb": 1,
    "lag_params%solver_approach": 2,
    "lag_params%cluster_type": 2,
    "lag_params%pressure_corrector": "T",
    "lag_params%smooth_type": 1,
    "lag_params%epsilonb": 1.0,
    "lag_params%heatTransfer_model": "T",
    "lag_params%massTransfer_model": "T",
    "lag_params%valmaxvoid": 0.99,
    "x_domain%beg": 0.0,
    "x_domain%end": 1.0,
    "y_domain%beg": 0.0,
    "y_domain%end": 1.0,
    "z_domain%beg": 0.0,
    "z_domain%end": 1.0,
    "bc_x%beg": -3,
    "bc_x%end": -3,
    "bc_y%beg": -3,
    "bc_y%end": -3,
    "bc_z%beg": -3,
    "bc_z%end": -3,
    "patch_icpp(1)%geometry": 9,
    "patch_icpp(1)%z_centroid": 0.05,
    "patch_icpp(1)%length_z": 0.1,
    "patch_icpp(2)%z_centroid": 0.45,
    "patch_icpp(2)%length_z": 0.7,
    "patch_icpp(3)%z_centroid": 0.9,
    "patch_icpp(3)%length_z": 0.2,
    "patch_icpp(1)%y_centroid": 0.5,
    "patch_icpp(1)%length_y": 1,
    "patch_icpp(1)%x_centroid": 0.5,
    "patch_icpp(1)%length_x": 1,
    "patch_icpp(1)%vel(1)": 0.0,
    "patch_icpp(1)%vel(2)": 0.0,
    "patch_icpp(1)%vel(3)": 0.0,
    "patch_icpp(2)%geometry": 9,
    "patch_icpp(2)%y_centroid": 0.5,
    "patch_icpp(2)%length_y": 1,
    "patch_icpp(2)%x_centroid": 0.5,
    "patch_icpp(2)%length_x": 1,
    "patch_icpp(2)%vel(1)": 0.0,
    "patch_icpp(2)%vel(2)": 0.0,
    "patch_icpp(2)%vel(3)": 0.0,
    "patch_icpp(3)%geometry": 9,
    "patch_icpp(3)%y_centroid": 0.5,
    "patch_icpp(3)%length_y": 1,
    "patch_icpp(3)%x_centroid": 0.5,
    "patch_icpp(3)%length_x": 1,
    "patch_icpp(3)%vel(1)": 0.0,
    "patch_icpp(3)%vel(2)": 0.0,
    "patch_icpp(3)%vel(3)": 0.0,
    "fluid_pp(2)%gamma": 2.5,
    "fluid_pp(2)%pi_inf": 0.0,
    "patch_icpp(1)%alpha_rho(2)": 0.0,
    "patch_icpp(1)%alpha(2)": 0.0,
    "patch_icpp(2)%alpha_rho(2)": 0.0,
    "patch_icpp(2)%alpha(2)": 0.0,
    "patch_icpp(3)%alpha_rho(2)": 0.0,
    "patch_icpp(3)%alpha(2)": 0.0,
    "acoustic(1)%loc(2)": 0.5,
    "acoustic(1)%wavelength": 0.25,
    "lag_txt_wrt": "T",
    "lag_header": "T",
    "lag_db_wrt": "T",
    "lag_id_wrt": "T",
    "lag_pos_wrt": "T",
    "lag_pos_prev_wrt": "T",
    "lag_vel_wrt": "T",
    "lag_rad_wrt": "T",
    "lag_rvel_wrt": "T",
    "lag_r0_wrt": "T",
    "lag_rmax_wrt": "T",
    "lag_rmin_wrt": "T",
    "lag_dphidt_wrt": "T",
    "lag_pres_wrt": "T",
    "lag_mv_wrt": "T",
    "lag_mg_wrt": "T",
    "lag_betaT_wrt": "T",
    "lag_betaC_wrt": "T",
    "lag_params%write_bubbles": "T",
    "lag_params%write_bubbles_stats": "T",
    "lag_params%write_void_evol": "T",
    "bub_pp%R0ref": 1.0,
    "bub_pp%p0ref": 1.0,
    "bub_pp%rho0ref": 1.0,
    "bub_pp%T0ref": 1.0,
    "bub_pp%ss": 7.131653759435349e-07,
    "bub_pp%pv": 0.02292716400352907,
    "bub_pp%vd": 2.4752475247524753e-06,
    "bub_pp%mu_l": 9.920792079207921e-08,
    "bub_pp%gam_v": 1.33,
    "bub_pp%gam_g": 1.4,
    "bub_pp%M_v": 18.02,
    "bub_pp%M_g": 28.97,
    "bub_pp%k_v": 5.618695895665441e-06,
    "bub_pp%k_g": 7.392868685947116e-06,
    "bub_pp%R_v": 1347.810235139403,
    "bub_pp%R_g": 838.3686723235085,
    "bub_pp%cp_g": 2921.2822272326243,
    "bub_pp%cp_v": 6134.692677188511,
    "acoustic(1)%support": 3,
    "acoustic(1)%height": 10000000000.0,
    "lag_params%vel_model": 2,
    "viscous": "T",
    "fluid_pp(1)%Re(1)": 100.0,
    "fluid_pp(2)%Re(1)": 100.0,
    "lag_params%drag_model": 0,
    "fd_order": 1
}

mods = {}
print(json.dumps({**case, **mods}))
